---
- name: install default config
  copy: src=zshrc
        dest=~/.zshrc

- name: create profile directory
  file: dest={{ profile_dir }}
        state=directory

- name: install default profile files
  copy: dest={{ profile_dir }}/{{ item }}
        src=profile.d/{{ item }}
  with_items:
    - env
    - ssh_agent

- name: install profile files for freebsd
  copy: dest={{ profile_dir }}/{{ item }}
        src=profile.d/{{ item }}
  with_items:
    - alias_freebsd
    - env_freebsd
  when: "ansible_system == 'FreeBSD'"

- name: install profile files for linux
  copy: dest={{ profile_dir }}/{{ item }}
        src=profile.d/{{ item }}
  with_items:
    - alias_linux
    - env_linux
  when: "ansible_system == 'Linux'"
