#!/bin/bash

# this is a simple config for herbstluftwm
function hc() {
    herbstclient "$@"
}

xsetroot -solid black
xsetroot -cursor_name left_ptr
xset -b
xmodmap .Xmodmap
bash ~/monitor.sh

# keybindings
Mod=Mod4
hc keybind $Mod-q quit
hc keybind $Mod-Shift-r reload
hc keybind $Mod-Shift-c close
hc keybind $Mod-Return spawn urxvt
hc keybind $Mod-x spawn dmenu_run -i -b -nb '#121212' -nf '#dedede' -sb '#232323' -sf '#f08000'
hc keybind Ctrl-Alt-l spawn xautolock -locknow
hc keybind Ctrl-Alt-s spawn $HOME/bin/monitor 0
hc keybind Ctrl-Alt-d spawn $HOME/bin/monitor 1
hc keybind Ctrl-Alt-p spawn $HOME/bin/hc-setup

# tags
TAG_NAMES=( {1..9} )
TAG_KEYS=( {1..9} 0 )

hc rename default "${TAG_NAMES[0]}" || true
for i in ${!TAG_NAMES[@]} ; do
    hc add "${TAG_NAMES[$i]}"
    key="${TAG_KEYS[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use "${TAG_NAMES[$i]}"
        hc keybind "$Mod-Shift-$key" move "${TAG_NAMES[$i]}"
    fi
done

# layouting
hc keybind $Mod-r remove
hc keybind $Mod-space cycle_layout 1
hc keybind $Mod-u split vertical 0.5
hc keybind $Mod-o split horizontal 0.5
hc keybind $Mod-s floating toggle
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-p pseudotile toggle

# resizing
RESIZESTEP=0.01
hc keybind $Mod-Control-h resize left +$RESIZESTEP
hc keybind $Mod-Control-j resize down +$RESIZESTEP
hc keybind $Mod-Control-k resize up +$RESIZESTEP
hc keybind $Mod-Control-l resize right +$RESIZESTEP

# mouse
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 resize
hc mousebind $Mod-Button3 zoom

# focus
hc set focus_follows_mouse 1
hc keybind $Mod-BackSpace   cycle_monitor
hc keybind $Mod-Tab         cycle_all +1
hc keybind $Mod-Shift-Tab   cycle_all -1
hc keybind $Mod-c cycle
hc keybind $Mod-h focus left
hc keybind $Mod-j focus down
hc keybind $Mod-k focus up
hc keybind $Mod-l focus right
hc keybind $Mod-Shift-h shift left
hc keybind $Mod-Shift-j shift down
hc keybind $Mod-Shift-k shift up
hc keybind $Mod-Shift-l shift right

# layout
# make a top padding
hc pad 0 15

# colors
hc set frame_border_active_color '#dd0000'
hc set frame_border_normal_color '#650000'
hc set frame_bg_normal_color '#BD9768'
hc set frame_bg_active_color '#BD8541'
hc set frame_border_width 1
hc set window_border_width 0
hc set window_gap 0
hc set window_border_normal_color '#AE8451'
hc set window_border_active_color '#F6FF00'

# rules
hc unrule -F
#hc rule class=XTerm tag=3 # move all xterms to tag 3
hc rule focus=off # normally do not focus new clients
# give focus to most common terminals
hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK)' manage=off

# start conky
killall conky
conky

# start the authentication deamon
#/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
# start the automatic screen lock
xautolock -time 2 -locker slock -killer "systemctl suspend" -killtime 20 &
autocutsel -fork &
autocutsel -selection PRIMARY -fork &
