#!/bin/bash

for f in $(find source.d -type f); do
  source "$f"
done

xsetroot -solid black
xsetroot -cursor_name left_ptr
xset -b
xmodmap .Xmodmap

# keybindings
Mod=Mod4
hc keybind $Mod-q quit
hc keybind $Mod-Shift-r reload
hc keybind $Mod-Shift-c close
hc keybind $Mod-Return spawn urxvt
hc keybind $Mod-x spawn dmenu_run -i -b -nb '#121212' -nf '#dedede' -sb '#232323' -sf '#f08000'
hc keybind Ctrl-Alt-l spawn xautolock -locknow
hc keybind Ctrl-Alt-s spawn $HOME/bin/monitor 0
hc keybind Ctrl-Alt-d spawn $HOME/bin/monitor 1
hc keybind Ctrl-Alt-p spawn $HOME/bin/hc-setup

# layouting
hc keybind $Mod-r remove
hc keybind $Mod-space cycle_layout 1
hc keybind $Mod-u split vertical 0.5
hc keybind $Mod-o split horizontal 0.5
hc keybind $Mod-s floating toggle
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-p pseudotile toggle

# resizing
RESIZESTEP=0.01
hc keybind $Mod-Control-h resize left +$RESIZESTEP
hc keybind $Mod-Control-j resize down +$RESIZESTEP
hc keybind $Mod-Control-k resize up +$RESIZESTEP
hc keybind $Mod-Control-l resize right +$RESIZESTEP

# mouse
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 resize
hc mousebind $Mod-Button3 zoom

# focus
hc set focus_follows_mouse 1
hc keybind $Mod-BackSpace   cycle_monitor
hc keybind $Mod-Tab         cycle_all +1
hc keybind $Mod-Shift-Tab   cycle_all -1
hc keybind $Mod-c cycle
hc keybind $Mod-h focus left
hc keybind $Mod-j focus down
hc keybind $Mod-k focus up
hc keybind $Mod-l focus right
hc keybind $Mod-Shift-h shift left
hc keybind $Mod-Shift-j shift down
hc keybind $Mod-Shift-k shift up
hc keybind $Mod-Shift-l shift right

# layout
# make a top padding for conky
hc pad 0 15

# colors
hc set frame_border_active_color '#dd0000'
hc set frame_border_normal_color '#650000'
hc set frame_bg_normal_color '#262626'
hc set frame_bg_active_color '#570000'
hc set frame_border_width 1
hc set window_border_width 0
hc set window_gap 0
hc set window_border_normal_color '#AE8451'
hc set window_border_active_color '#F6FF00'

# rules
hc unrule -F
hc rule focus=off # normally do not focus new clients
# give focus to most common terminals
hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK)' manage=off

# start conky
killall conky
conky

# start the automatic screen lock
xautolock -time 2 -locker "i3lock --color 000000" -killer "systemctl suspend" -killtime 20 &
autocutsel -fork &
autocutsel -selection PRIMARY -fork &
