#!/bin/bash

for f in $(find ~/.config/herbstluftwm/source.d -type f | sort); do
  source "$f"
done

# keybindings
#hc keybind Ctrl-Alt-s spawn $HOME/bin/monitor 0
#hc keybind Ctrl-Alt-d spawn $HOME/bin/monitor 1
#hc keybind Ctrl-Alt-p spawn $HOME/bin/hc-setup
